// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {


  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8zOjkbQG0vaTwQiG3sjh9GMBuzp-VRDE',
    appId: '1:768157305611:web:7e35aea74f05787c1d700e',
    messagingSenderId: '768157305611',
    projectId: 'vixvox-4ad2a',
    authDomain: 'vixvox-4ad2a.firebaseapp.com',
    storageBucket: 'vixvox-4ad2a.appspot.com',
    measurementId: 'G-YJGTZH7J81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1PYgNXtYMsFMyXHcLEQPypPOtDAG3cls',
    appId: '1:768157305611:android:e79490ed0221a1b01d700e',
    messagingSenderId: '768157305611',
    projectId: 'vixvox-4ad2a',
    storageBucket: 'vixvox-4ad2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrtA20YoDMmlg6a9DL32cR9-6yTVb16uk',
    appId: '1:768157305611:ios:89e8b6450b3413551d700e',
    messagingSenderId: '768157305611',
    projectId: 'vixvox-4ad2a',
    storageBucket: 'vixvox-4ad2a.appspot.com',
    iosBundleId: 'com.example.vixvox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrtA20YoDMmlg6a9DL32cR9-6yTVb16uk',
    appId: '1:768157305611:ios:8c9b07c2a057c7cb1d700e',
    messagingSenderId: '768157305611',
    projectId: 'vixvox-4ad2a',
    storageBucket: 'vixvox-4ad2a.appspot.com',
    iosBundleId: 'com.example.vixvox.RunnerTests',
  );
}
